### PR TITLE
bg(getSpecificLoan): User can Only retrieve their own loan

### PR DESCRIPTION
**Pull request by ibkadeeko**
#### What does this PR do?
User Can Only retrieve their own loan 

#### Description of Task to be completed
A user should be able to only retrieve their own loan applications. Any attempt by a user to retrieve another users loan should throw an error.

#### How should this be manually tested?
1. Clone this branch.
2. Run `npm install` to install the dependencies.
3. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#166212913](https://pivotaltracker.com/story/show/166212913)

#### Screenshots (if appropriate)
Screenshot from 2019-05-23 17-21-14

### CODE REVIEW

**Comment by luqmanoop** [comment]
Update your PR title

**Comment by ibkadeeko** [comment]
I just corrected the error. Or do you mean I should change the whole title

**Review by luqmanoop — APPROVED** [review]
LGTM

**Comment by ibkadeeko** [comment]
Ok

**Pull request merged**
