### PR TITLE
bg(repayments): User can only get their repayments history

### PR DESCRIPTION
**Pull request by ibkadeeko**
#### What does this PR do?
User can only retrieve his/her repayments history

#### Description of Task to be completed
- When a user sends a request to get loan repayments of another user, it should return an error

#### How should this be manually tested?
1. Clone this branch.
2. Run `npm install` to install the dependencies.
3. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#166223421](https://pivotaltracker.com/story/show/166223421)

#### Screenshots (if appropriate)
Screenshot from 2019-05-23 22-24-32

### CODE REVIEW

**Comment by luqmanoop** [comment]
Does your commit message follow the set convention?

**Comment by luqmanoop** [comment]
> Does your commit message follow the set convention?

Is this output tied/linked to a ticket on PT? If yes, will your commit message automatically close the ticket when this PR is merged?

**Comment by ibkadeeko** [comment]
My week 1 LFA showed me that it should be an example like
ft(title): description.
The way it is now it wouldn't automatically close the ticket when the PR is closed, except i add 
[finishes #pt-tracker-id].
I didn't know it was compulsory to close the ticket automatically

**Comment by luqmanoop** [comment]
> My week 1 LFA showed me that it should be an example like
> ft(title): description.
> The way it is now it wouldn't automatically close the ticket when the PR is closed, except i add
> [finishes #pt-tracker-id].
> I didn't know it was compulsory to close the ticket automatically

I can't see [Fixes #pt-tracker-id] in your commit message

**Comment by ibkadeeko** [comment]
I'll add that now

**Comment by ibkadeeko** [comment]
I have made the change

**Pull request merged**
